output_path: "outputs/"
yolo_path: "scripts/models/FootAI_yolo11x/weights/best.pt"
keypoints_path: "scripts/models/Keypoints_yolo11x/weights/best.pt"
retina_path: "scripts/models/RetinaNet/model_best.pth"
confidence: 0.45 #0.45 yolo best performance model v11x
